CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "google_id" varchar(30) NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "username" varchar(255) NOT NULL
);

CREATE TABLE "games" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "host_user_id" INT NOT NULL,
  "number_rounds" INT NOT NULL,
  "time_limit_seconds" INT NOT NULL,
  "started_at" timestamp NOT NULL DEFAULT (now()),
  "ended_at" timestamp,
  "status_id" INT NOT NULL
);

CREATE TABLE "game_players" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" INT NOT NULL,
  "user_id" INT NOT NULL,
  "score" INT NOT NULL DEFAULT 0
);

CREATE TABLE "rounds" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "game_id" INT NOT NULL,
  "word_id" INT NOT NULL,
  "round_number" INT NOT NULL
);

CREATE TABLE "round_definitions" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "round_id" INT NOT NULL,
  "user_id" INT,
  "definition" varchar(512) NOT NULL,
  "word_id" INT NOT NULL,
  "submitted_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "votes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "round_id" INT NOT NULL,
  "voter_user_id" INT NOT NULL,
  "round_definition_id" INT NOT NULL,
  "voted_at" timestamp NOT NULL DEFAULT (now())
);

CREATE TABLE "words" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "word" varchar(45) NOT NULL,
  "definition" varchar(512) NOT NULL
);

CREATE TABLE "statuses" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "status" varchar(20) NOT NULL
);

ALTER TABLE "games" ADD FOREIGN KEY ("host_user_id") REFERENCES "users" ("id");

ALTER TABLE "games" ADD FOREIGN KEY ("status_id") REFERENCES "statuses" ("id");

ALTER TABLE "game_players" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "game_players" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "rounds" ADD FOREIGN KEY ("game_id") REFERENCES "games" ("id");

ALTER TABLE "rounds" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "round_definitions" ADD FOREIGN KEY ("round_id") REFERENCES "rounds" ("id");

ALTER TABLE "round_definitions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "round_definitions" ADD FOREIGN KEY ("word_id") REFERENCES "words" ("id");

ALTER TABLE "votes" ADD FOREIGN KEY ("round_id") REFERENCES "rounds" ("id");

ALTER TABLE "votes" ADD FOREIGN KEY ("voter_user_id") REFERENCES "users" ("id");

ALTER TABLE "votes" ADD FOREIGN KEY ("submission_id") REFERENCES "round_definitions" ("id");