INSERT INTO public.words(word, definition)VALUES ('wadmiltilt', 'A strong rough woolen cloth employed to cover powder-barrels and to protect ammunition');
INSERT INTO public.words(word, definition)VALUES ('scrivello', 'An elephants tusk of less than 20 pounds in weight');
INSERT INTO public.words(word, definition)VALUES ('scapulimancy', 'Divination by means of a shoulder-blade');
INSERT INTO public.words(word, definition)VALUES ('queez-madam', 'The cuisse-madam, a French jargonelle pear');
INSERT INTO public.words(word, definition)VALUES ('progger', 'One who progs; a rambling or aimless searcher; specifically, one who progs for clams, oysters, etc, alongshore; a pot-fisherman');
INSERT INTO public.words(word, definition)VALUES ('piloerection', 'The erection of hairs or papillae');
INSERT INTO public.words(word, definition)VALUES ('furcatorium', 'The furciform bone, wishbone, or merrythought of a fowl: more fully called os furcatorium See cut under furcula');
INSERT INTO public.words(word, definition)VALUES ('fungible', 'Law  Returnable or negotiable in kind or by substitution, as a quantity of grain for an equal amount of the same kind of grain');
INSERT INTO public.words(word, definition)VALUES ('croche', 'An obsolete form of crutch');
INSERT INTO public.words(word, definition)VALUES ('bum-clock', 'An insect which bums or hums, as a chafer or bee');
INSERT INTO public.words(word, definition)VALUES ('aglet', 'A tag or sheath, as of plastic, on the end of a lace, cord, or ribbon to facilitate its passing through eyelet holes');
INSERT INTO public.words(word, definition)VALUES ('oikomania', 'Monomania in relation to household affairs');
INSERT INTO public.words(word, definition)VALUES ('aprosexia', 'Lack of power to keep the attention fixed on any subject; an extreme degree of mind-wandering');
INSERT INTO public.words(word, definition)VALUES ('sessle', 'To change seats very often');
INSERT INTO public.words(word, definition)VALUES ('snotter', 'The red part of a turkey-cocks head');
INSERT INTO public.words(word, definition)VALUES ('widdershins', 'In a contrary or counterclockwise direction');
INSERT INTO public.words(word, definition)VALUES ('slargando', 'Gradually slackening in tempo; ritardando Used chiefly as a direction');
INSERT INTO public.words(word, definition)VALUES ('warkamoowee', 'A canoe with outriggers, used at Point de Galle, island of Ceylon');
INSERT INTO public.words(word, definition)VALUES ('dunga-runga', 'A small tree of crooked growth, Notelæa ovata, yielding close-grained, hard wood, used for tool-handles See Notelæa');
INSERT INTO public.words(word, definition)VALUES ('zucchetta', 'In the Roman Catholic Church, the skullcap of an ecclesiastic, covering the tonsure That of a priest is black, of a bishop purple, of a cardinal red, and of the Pope white Also written zucchetto');
INSERT INTO public.words(word, definition)VALUES ('penistone', 'A coarse woolen stuff or frieze It was in use in England during the sixteenth and seventeenth centuries Also peniston, peneston, pennistone, pennystone, and forest whites');
INSERT INTO public.words(word, definition)VALUES ('rockhair', 'A rock-loving lichen, Alectoria jubata See Alectoria');
INSERT INTO public.words(word, definition)VALUES ('fyrdung', 'In Anglo-Saxon history, the army prepared for war; a military expedition; a camp');
INSERT INTO public.words(word, definition)VALUES ('tantony', 'A petted follower; a servile adherent');
INSERT INTO public.words(word, definition)VALUES ('jipijapa', 'A stemless palmlike plant (Carludovica palmata) of Central and South America, having long-stalked, fanlike leaves that are used to make Panama hats');
INSERT INTO public.words(word, definition)VALUES ('smuth', 'A minersname for waste, poor, or small coal See smut, 4');
INSERT INTO public.words(word, definition)VALUES ('glossanthrax', 'A disease in horses and cattle characterized by malignant carbuncles in the mouth, and especially on the tongue');
INSERT INTO public.words(word, definition)VALUES ('sagbut', 'A medieval instrument resembling the trombone');
INSERT INTO public.words(word, definition)VALUES ('googwaruck', 'The mottled honey-eater or brush wattle-bird (A carunculata) of Australia, a melliphagine bird of the genus Anthochœra');
INSERT INTO public.words(word, definition)VALUES ('woom', 'A trade-name for the fur of the beaver There are four sorts—silvery, pale, white, and brown');
INSERT INTO public.words(word, definition)VALUES ('sexfoil', 'A plant or flower with six leaves');
INSERT INTO public.words(word, definition)VALUES ('baldachin', 'A rich fabric of silk and gold brocade');
INSERT INTO public.words(word, definition)VALUES ('androconia', 'Certain specialized scales oscurring in limited areas on the wings of the males of certain Lepidoptera');
INSERT INTO public.words(word, definition)VALUES ('anableps', 'A genus of cyprinodont fishes unique among vertebrates on account of the division of the cornea into upper and lower halves by a dark horizontal stripe of the conjunctiva, and the development of two pupils to each orbit, so that the fish appears to have four eyes, one pair looking upward and the other pair sidewise');
INSERT INTO public.words(word, definition)VALUES ('mehari', 'One of a race of swift Arabian camels taking name from Mehara, a region in Arabia where it is raised, and of great value in campaigning and in exploring expeditions');
INSERT INTO public.words(word, definition)VALUES ('boondocking', 'Present participle of boondock');
INSERT INTO public.words(word, definition)VALUES ('zamouse', 'A West African buffalo, or bush-ox, found in Sierra Leone, Bos brachyceros, the short-horned buffalo, having the ears fringed with hair, short horns depressed at base, and no dewlap');
INSERT INTO public.words(word, definition)VALUES ('choil', 'In cutlery, the indentation in the blade of a knife where it joins the tang');
INSERT INTO public.words(word, definition)VALUES ('miryachit', 'A neurosis observed in Siberia, characterized by extreme excitability and sometimes exhibitions of terror, with imitation of word and deed and often obscene speech');
INSERT INTO public.words(word, definition)VALUES ('furfur', 'An epidermal scale, as that associated with dandruff');
INSERT INTO public.words(word, definition)VALUES ('frenulum', 'A bristly structure on the hind wings of certain moths and butterflies that holds the forewings and hind wings together during flight');
INSERT INTO public.words(word, definition)VALUES ('ozostomia', 'Foul-smelling breath; halitosis');
INSERT INTO public.words(word, definition)VALUES ('coom', 'The wooden frame used in building the arch of a bridge');
INSERT INTO public.words(word, definition)VALUES ('molebut', 'The short sunfish, a typical species of Molidæ, technically called Mola mola, M rotunda, or Orthagoriscus mola Also mole-bat See cut at Mola');
INSERT INTO public.words(word, definition)VALUES ('bipennis', 'An ancient ax with two blades, one on each side of the handle');
INSERT INTO public.words(word, definition)VALUES ('hackmatack', 'Any of several North American trees, especially the tamarack');
INSERT INTO public.words(word, definition)VALUES ('yapok', 'An aquatic opossum (Chironectes minimus) of tropical regions of the Americas, having dense fur, webbed hind feet, and a long tail');
INSERT INTO public.words(word, definition)VALUES ('finochio', 'Fœniculum dulce, a variety of fennel; sweet fennel');
INSERT INTO public.words(word, definition)VALUES ('cisvestism', 'The wearing of clothing that does not represent ones profession or status');
INSERT INTO public.words(word, definition)VALUES ('pungi', 'A Hindu pipe or nose-flute composed of a gourd or nut-shell into which two wooden pipes or reeds are inserted It emits a droning or humming sound, and is the instrument commonly used by snake-charmers');
INSERT INTO public.words(word, definition)VALUES ('fluther', 'Hurry; bustle');
INSERT INTO public.words(word, definition)VALUES ('satrap', 'A governor of a province in ancient Persia');
INSERT INTO public.words(word, definition)VALUES ('whiffler', 'A piper or fifer');
INSERT INTO public.words(word, definition)VALUES ('silybum', 'A genus of thistles, belonging to the order Compositæ, tribe Cynaroideæ, and subtribe Carduineæ');
INSERT INTO public.words(word, definition)VALUES ('furfural', 'A colorless, sweet-smelling, oily liquid, C5H4O2, made from corncobs and other cellulosic wastes and used in the synthesis of furan derivatives, as a solvent for nitrocellulose, cellulose acetate, and certain dyes, and as a fungicide and insecticide');
INSERT INTO public.words(word, definition)VALUES ('cockchafer', 'Any of several large European scarab beetles of the genus Melolontha, especially M melolontha, having larvae that damage plant roots and adults that feed on leaves');
INSERT INTO public.words(word, definition)VALUES ('zyzzyva', 'Any of several tropical American weevils of the genus Zyzzyva');
INSERT INTO public.words(word, definition)VALUES ('hodmandod', 'A snail; a dodman');
INSERT INTO public.words(word, definition)VALUES ('ginglymus', 'In anatomy, a hinge-joint or ginglymoid articulation; a diarthrodial joint permitting movement in one plane only, the result being simple flexion and extension');
INSERT INTO public.words(word, definition)VALUES ('sirgang', 'The so-called green jackdaw of Asia, Cissa sinensis');
INSERT INTO public.words(word, definition)VALUES ('biggin', 'A kind of coffee-pot containing a strainer for the infusion of the coffee, without allowing the grounds to mix with the infusion');
INSERT INTO public.words(word, definition)VALUES ('liripoop', 'A pendent part of the old clerical tippet; afterwards, a tippet; a scarf; -- worn also by doctors, learned men, etc');
INSERT INTO public.words(word, definition)VALUES ('prunella', 'A strong heavy fabric of worsted twill, used chiefly for shoe uppers, clerical robes, and academic gowns');
INSERT INTO public.words(word, definition)VALUES ('hawsehole', 'An opening in the bow of a ship through which a cable or hawser is passed');
INSERT INTO public.words(word, definition)VALUES ('didunculus', 'A remarkable genus of pigeons, constituting the subfamily Didunculinœ of the family Columbidœ, or made the type of a different family, Didunculidœ');
INSERT INTO public.words(word, definition)VALUES ('spraints', 'The dung of an otter');
INSERT INTO public.words(word, definition)VALUES ('haruspicy', 'The study and divination by use of animal entrails, usually the victims of sacrifice');
INSERT INTO public.words(word, definition)VALUES ('pogonophile', 'One who loves or studies beards');
INSERT INTO public.words(word, definition)VALUES ('gaster', 'The portion of the abdomen behind the petiole in ants and other hymenopterous insects');
INSERT INTO public.words(word, definition)VALUES ('timbromania', 'a passion for stamp collecting');
INSERT INTO public.words(word, definition)VALUES ('swazzle', 'Device to change the voice to make it more raspy, used in Punch and Judy performances');
INSERT INTO public.words(word, definition)VALUES ('hagbut', ' A firearm with a long barrel');
INSERT INTO public.words(word, definition)VALUES ('scopula', 'A dense brushlike tuft of hairs, as on the feet of certain spiders and insects');
INSERT INTO public.words(word, definition)VALUES ('bunji-bunji', 'an Australian timber tree (Flindersia schottiana) whose bark yields a poison');
INSERT INTO public.words(word, definition)VALUES ('kiltie', 'One who wears a kilt');
INSERT INTO public.words(word, definition)VALUES ('bogong', 'An Australian noctuid moth, Agrotis spina, which occurs in enormous numbers in Victoria, where the hibernating adults were eaten by the aborigines');
INSERT INTO public.words(word, definition)VALUES ('soushumber', 'A woolly and spiny species of nightshade, Solanum mammosum, of tropical America It is a noxious weed, bearing worthless yellow inversely pear-shaped berries');
INSERT INTO public.words(word, definition)VALUES ('fiants', 'In hunting, the dung of the boar, wolf, fox, marten, or badger');
INSERT INTO public.words(word, definition)VALUES ('allocochick', 'The name of Indian shell-money used in northern California');
INSERT INTO public.words(word, definition)VALUES ('sarcology', 'The science of the soft or fleshy parts of the body: a department of anatomy distinguished from osteology');
INSERT INTO public.words(word, definition)VALUES ('coxopodite', 'In Arthropoda, as a crustacean, the proximal joint of a developed limb by which the limb articulates with its somite or segment of the body');
INSERT INTO public.words(word, definition)VALUES ('glabrescent', 'In botany, becoming glabrous, as organs that are hairy in the bud or young state and glabrous with age');
INSERT INTO public.words(word, definition)VALUES ('pipsissewa', 'Any of several evergreen plants of the genus Chimaphila in the heath family, especially C umbellata, having white or pinkish flowers and formerly used as a medicinal herb');
INSERT INTO public.words(word, definition)VALUES ('gutta-percha', 'A rubbery substance derived from the latex of any of several tropical trees chiefly of the genus Palaquium of Southeast Asia, used in dental devices and formerly as an electrical insulator and in golf balls');
INSERT INTO public.words(word, definition)VALUES ('exophagy', 'A custom of certain cannibal tribes, prohibiting the eating of persons of their own tribe');
INSERT INTO public.words(word, definition)VALUES ('chiloma', 'In zoology, the upper lip or muzzle of a quadruped, when tumid and continued uninterruptedly from the nostril, as in the camel');
INSERT INTO public.words(word, definition)VALUES ('trichobezoar', 'A bezoar composed of hair');
INSERT INTO public.words(word, definition)VALUES ('spong', 'A projection of land; an irregular, narrow, projecting part of a field');
INSERT INTO public.words(word, definition)VALUES ('carriwitchet', 'An absurd question; a quibble; a conundrum; a pun; a piece of jocularity or facetiousness');
INSERT INTO public.words(word, definition)VALUES ('foumart', 'See foulmart');
INSERT INTO public.words(word, definition)VALUES ('purlicue', 'A summing up or capitulation of discourses previously delivered');
INSERT INTO public.words(word, definition)VALUES ('jujuism', 'The system of beliefs and practices relating to the juju');
INSERT INTO public.words(word, definition)VALUES ('ranarium', 'A collection of live frogs; a place where frogs are kept alive, to study their transformations, for vivisection in physiological experiments, etc');
INSERT INTO public.words(word, definition)VALUES ('haptodysphoria', 'An odd sensation felt by certain people when handling peaches or other fuzzy surfaces');
INSERT INTO public.words(word, definition)VALUES ('wallwort', 'The dwarf elder, or danewort, Sambucus Ebulus; sometimes, also, the wall pellitory, Parietaria officinalis; the stonecrop, Sedum acre; and the navelwort, Cotyledon Umbilicus');
INSERT INTO public.words(word, definition)VALUES ('emacity', 'Desire or fondness for buying');
INSERT INTO public.words(word, definition)VALUES ('wonga-wonga', 'A large Australian pigeon, Lcucosarcia picata, having white flesh, and much esteemed for the table');
INSERT INTO public.words(word, definition)VALUES ('zugzwang', 'A situation in a chess game in which a player is forced to make an undesirable or disadvantageous move');
INSERT INTO public.words(word, definition)VALUES ('zumbooruk', 'A small cannon mounted on a swivel, usually shorter and with larger bore than the zingal');
INSERT INTO public.words(word, definition)VALUES ('sniggle', 'To fish for eels by thrusting a baited hook into their hiding places');
INSERT INTO public.words(word, definition)VALUES ('tzitzit', 'The knotted tassels of thread, symbolizing the 613 commandments in the Hebrew Scriptures, attached to the corners of a tallit or other garment');
INSERT INTO public.words(word, definition)VALUES ('fackeltanz', 'A torchlight procession, a survival from medieval tournaments, which is celebrated at some of the German courts on the marriage of a member of the royal family');
INSERT INTO public.words(word, definition)VALUES ('zufolo', 'A little flute or flageolet, especially such as is used in teaching birds');
INSERT INTO public.words(word, definition)VALUES ('tegestologist', 'someone who collects beer mats or coasters');
INSERT INTO public.words(word, definition)VALUES ('hornito', 'A low mound of volcanic origin, sometimes emitting smoke or vapor');
INSERT INTO public.words(word, definition)VALUES ('bignonia', 'An evergreen woody vine (Bignonia capreolata) native to the southeast United States, having showy reddish orange trumpet-shaped flowers and stems that show a cross shape when cut in cross-section');
INSERT INTO public.words(word, definition)VALUES ('hectocotylus', 'A modified arm of the male of certain cephalopods, such as most octopuses, functioning as a reproductive organ in transferring sperm to the mantle cavity of the female');
INSERT INTO public.words(word, definition)VALUES ('slugga', 'In Ireland, a swallowhole, or abrupt deep cavity formed in certain limestone districts by the falling of parts of the surface-rock into depressions which have been made by subterranean rivers');
INSERT INTO public.words(word, definition)VALUES ('nurdle', 'conversation  To gently waffle or muse on a subject which one clearly knows little about');
INSERT INTO public.words(word, definition)VALUES ('shittah', 'A tree, probably a species of acacia, that was a source of a wood mentioned frequently in the Bible');
INSERT INTO public.words(word, definition)VALUES ('whizzer', 'A centrifugal machine used for drying sugar, grain, clothes, etc');
INSERT INTO public.words(word, definition)VALUES ('chitarrone', 'A large chitarra, usually with a double neck, much extended, very similar to that of the theorbo and archlute');
INSERT INTO public.words(word, definition)VALUES ('niblick', 'An iron-headed golf club with the face slanted at a greater angle than any other iron except a wedge; a nine iron');
INSERT INTO public.words(word, definition)VALUES ('cannelure', 'A groove around the cylinder of a bullet');
INSERT INTO public.words(word, definition)VALUES ('sniddle', 'Long coarse grass; sedges and allied plants of wet places Halliwell; Britten and Holland, Eng Plant Names');
INSERT INTO public.words(word, definition)VALUES ('scuppernong', 'A cultivated variety of the muscadine grape with sweet yellowish fruit');
INSERT INTO public.words(word, definition)VALUES ('morpunkee', 'A native pleasure-boat formerly much used for state occasions on the rivers of India');
INSERT INTO public.words(word, definition)VALUES ('pahoehoe', 'Lava with a smooth ropy surface');
INSERT INTO public.words(word, definition)VALUES ('ailurophile', 'One who loves cats');
INSERT INTO public.words(word, definition)VALUES ('schwenkfelder', 'A member of a German denomination founded in Silesia in the sixteenth century by Kaspar Schwenkfeld');
INSERT INTO public.words(word, definition)VALUES ('zobo', 'A breed of zebu-cattle, supposed to be a hybrid of the common zebu with the yak, reared in the western Himalayan region for its flesh and milk, and also as a beast of burden');
INSERT INTO public.words(word, definition)VALUES ('tarantism', 'A disorder characterized by an uncontrollable urge to dance, especially prevalent in southern Italy from the 15th to the 17th century and popularly attributed to the bite of a tarantula');
INSERT INTO public.words(word, definition)VALUES ('koomkie', 'A tame female elephant used as a decoy in the capture of wild male elephants');
INSERT INTO public.words(word, definition)VALUES ('rupophobia', 'A morbid dread of uncleanliness');
INSERT INTO public.words(word, definition)VALUES ('extispicy', 'Divination by means of inspecting the entrails of sacrificed animals');
INSERT INTO public.words(word, definition)VALUES ('zarf', 'A chalicelike holder for a hot coffee cup, typically made of ornamented metal, used in the Middle East');
INSERT INTO public.words(word, definition)VALUES ('pogonotomy', 'The cutting of beards; shaving');
INSERT INTO public.words(word, definition)VALUES ('zenzizenzizenzic', 'mathematics, obsolete  the eighth power of a number');
INSERT INTO public.words(word, definition)VALUES ('tacamahac', 'Any of several aromatic resinous substances used in ointments and incense');
INSERT INTO public.words(word, definition)VALUES ('acrocephalic', 'In ethnology, pertaining to or characterized by acrocephaly; high-skulled: as, acrocephalic men or tribes');
INSERT INTO public.words(word, definition)VALUES ('deipnophobia', 'rare  A fear of dinner parties');
INSERT INTO public.words(word, definition)VALUES ('plumbum', 'Lead');
INSERT INTO public.words(word, definition)VALUES ('hypohippus', 'A genus of extinct perissodactyl ungulate mammals, of the family Anchitheriidæ');
INSERT INTO public.words(word, definition)VALUES ('trocar', 'A sharp-pointed surgical instrument, used with a cannula to puncture a body cavity for fluid aspiration');
INSERT INTO public.words(word, definition)VALUES ('coprolite', 'Fossilized excrement');
INSERT INTO public.words(word, definition)VALUES ('otolith', 'One of the small calcareous particles found in the inner ear of many vertebrates, especially fishes, which are involved in determining body orientation and sometimes in perceiving sound');
INSERT INTO public.words(word, definition)VALUES ('sialogogue', 'Producing a flow of saliva; ptyalogogue');
INSERT INTO public.words(word, definition)VALUES ('drapetomania', 'dated  an overwhelming urge to run away (from home, a bad situation, responsibility, etc)');
INSERT INTO public.words(word, definition)VALUES ('chimb', 'An obsolete form of chime');
INSERT INTO public.words(word, definition)VALUES ('bletting', 'The slow internal decay or “sleepiness” that takes place in some fruits, as apples and pears, after they are gathered');
INSERT INTO public.words(word, definition)VALUES ('blennophobia', 'The irrational fear of slime');
INSERT INTO public.words(word, definition)VALUES ('paddlecock', 'The common lump-fish, Cyclopterus lumpus: so called in allusion to its dorsal ridge enveloped in tubercular skin, which resembles the comb of the domestic cock See cut under Cyclopterus');
INSERT INTO public.words(word, definition)VALUES ('crizzle', 'A roughness on the surface of glass which clouds its transparency Also crizzel');
INSERT INTO public.words(word, definition)VALUES ('fundungi', 'an expert or guru');
INSERT INTO public.words(word, definition)VALUES ('octothorpe', 'The symbol (#)');
INSERT INTO public.words(word, definition)VALUES ('mamamouchi', 'A pompous title, from that supposed to have been conferred by the Sultan on M Jourdain in Molières play, ‘Le Bourgeois Gentilhomme’; hence, one who takes such a title; an ostentatious, self-important, and ridiculous pretender');
INSERT INTO public.words(word, definition)VALUES ('stadda', 'A doublebladed hand-saw, used for cutting comb-teeth Also called steady');
INSERT INTO public.words(word, definition)VALUES ('oikofugic', 'Relating to or characterized by the desire to travel, migrate, play truant, etc: opposed to oikotropic');
INSERT INTO public.words(word, definition)VALUES ('splanchnic', 'Of or relating to the viscera; visceral');
INSERT INTO public.words(word, definition)VALUES ('jollop', 'The cry of a turkey');
INSERT INTO public.words(word, definition)VALUES ('googol', 'The number 10 raised to the power 100 (10100), written out as the numeral 1 followed by 100 zeros');
INSERT INTO public.words(word, definition)VALUES ('lychnobite', 'One who labors at night and sleeps in the day');
INSERT INTO public.words(word, definition)VALUES ('fardingbag', 'The upper stomach of a cow');
INSERT INTO public.words(word, definition)VALUES ('furuncle', 'A circumscribed inflammation of the skin, forming a necrotic central core, and suppurating and discharging the core; a boil');
INSERT INTO public.words(word, definition)VALUES ('howdah', 'A seat, usually fitted with a canopy and railing, placed on the back of an elephant or a camel');
INSERT INTO public.words(word, definition)VALUES ('piblockto', 'In Greenland, a frenzied condition of dogs which results from continued exposure to extremely cold weather');
INSERT INTO public.words(word, definition)VALUES ('omphaloskepsis', 'Contemplation of or meditation upon ones navel');
INSERT INTO public.words(word, definition)VALUES ('philtrum', 'The groove running from the septum of the nose down the central line of the upper lip');
INSERT INTO public.words(word, definition)VALUES ('totipalmation', 'Complete palmation or full webbing of a birds foot by three ample webs connecting all four toes, as of one of the Totipalmaæ: a leading character of that order of birds: correlated with palmation, 2, and semipalmation See cuts under Phaëthon and totipalmate');
INSERT INTO public.words(word, definition)VALUES ('dooab', 'See doab');
INSERT INTO public.words(word, definition)VALUES ('quipu', 'A cord about 2 feet in length, tightly spun from variously colored threads, and having a number of smaller threads attached to it in the form of a fringe: used among the ancient Peruvians and elsewhere for recording events, etc');
INSERT INTO public.words(word, definition)VALUES ('bathetic', 'Characterized by bathos');
INSERT INTO public.words(word, definition)VALUES ('glossarium', 'In cntom, the long slender labrum of a mosquito or other predatory dipterous insect');
INSERT INTO public.words(word, definition)VALUES ('flews', 'The pendulous corners of the upper lip of certain dogs, such as the bloodhound');
INSERT INTO public.words(word, definition)VALUES ('ugli', 'A cross between a tangerine and grapefruit, grown in the West Indies');
INSERT INTO public.words(word, definition)VALUES ('tittup', 'To move in a lively, capering manner; prance');
INSERT INTO public.words(word, definition)VALUES ('vibrissae', 'Plural form of vibrissa');
INSERT INTO public.words(word, definition)VALUES ('spiloma', 'A congenital local discoloration of the skin');
INSERT INTO public.words(word, definition)VALUES ('gopak', 'Alternative form of hopak');
INSERT INTO public.words(word, definition)VALUES ('snast', 'The snuff of a candle');
INSERT INTO public.words(word, definition)VALUES ('slype', 'A covered passage, especially one between the transept and chapter house of a cathedral');
INSERT INTO public.words(word, definition)VALUES ('xylivorous', 'That eats wood');
INSERT INTO public.words(word, definition)VALUES ('soogee-moogee', 'nautical, slang, dated  A type of strong cleaning product for wood and paint on board a boat');
INSERT INTO public.words(word, definition)VALUES ('sigogglin', 'archaic, US, Appalachia  not built correctly, crooked, skewed, out of balance');
INSERT INTO public.words(word, definition)VALUES ('piscatology', 'The scientific study of fishes; ichthyology');
INSERT INTO public.words(word, definition)VALUES ('ichiboo', 'See bu');
INSERT INTO public.words(word, definition)VALUES ('thooid', 'Wolfish; resembling or related to the wolf; lupine: as, “the thoöid or lupine series” of canines, W H Flower');
INSERT INTO public.words(word, definition)VALUES ('fizzog', 'The art of judging the character of a person by the countenance or appearance');
INSERT INTO public.words(word, definition)VALUES ('fichu', 'A womans triangular scarf of lightweight fabric, worn over the shoulders and crossed or tied in a loose knot at the breast');
INSERT INTO public.words(word, definition)VALUES ('carapace', 'Zoology  A hard bony or chitinous outer covering, such as the fused dorsal plates of a turtle or the portion of the exoskeleton covering the head and thorax of a crustacean');
INSERT INTO public.words(word, definition)VALUES ('runtee', 'A disk of shell used as an ornament by the Indians of Virginia in the seventeenth and eighteenth centuries');
INSERT INTO public.words(word, definition)VALUES ('vuggs', 'Plural form of vugg');
INSERT INTO public.words(word, definition)VALUES ('gaberlunzie', 'Scotland, historical  A licenced beggar');
INSERT INTO public.words(word, definition)VALUES ('kamalayka', 'A waterproof shirt made of intestines of seal or walrus');
INSERT INTO public.words(word, definition)VALUES ('ghurry', 'In India— A clepsydra, or water-instrument for measuring time');
INSERT INTO public.words(word, definition)VALUES ('sprog', 'UK, Australia, Canada, New Zealand, informal  A child');
INSERT INTO public.words(word, definition)VALUES ('galactophagist', 'One who eats or subsists on milk');
INSERT INTO public.words(word, definition)VALUES ('boomkin', 'A short outrigger projecting from the side of the aft part of a square-rigged sailing ship');
INSERT INTO public.words(word, definition)VALUES ('whickflaw', 'A swelling or inflammation about the nails or ends of the fingers; paronychia; whitlow See whitlow');
INSERT INTO public.words(word, definition)VALUES ('bufagin', 'organic chemistry  Any of a class of toxic steroids found in bufotoxin');
INSERT INTO public.words(word, definition)VALUES ('bissextile', 'Of or relating to a leap year');
INSERT INTO public.words(word, definition)VALUES ('bezoar', 'A hard indigestible mass of material, such as hair, plant fibers, or seeds, found in the stomach or intestine of animals, especially ruminants and sometimes humans Bezoars were formerly considered to be antidotes to poisons and to possess magic properties');
INSERT INTO public.words(word, definition)VALUES ('baronduki', 'The terrestrial Siberian squirrel');
INSERT INTO public.words(word, definition)VALUES ('natterjack', 'A very common European toad, Bufo calamita, belonging to the family Bufonidæ');
INSERT INTO public.words(word, definition)VALUES ('sortita', 'In music: The first air sung by any one of the principal singers in an opera; an entrance-air');
INSERT INTO public.words(word, definition)VALUES ('boomslang', 'An African tree-snake, Bucephalus capensis');
INSERT INTO public.words(word, definition)VALUES ('waldheimia', 'A genus of hymenopterous insects');
INSERT INTO public.words(word, definition)VALUES ('sozzle', 'A state of sloppy disorder');
INSERT INTO public.words(word, definition)VALUES ('soosoo', 'See susu');
INSERT INTO public.words(word, definition)VALUES ('caruncle', 'Biology  A fleshy naked outgrowth, such as a fowls wattles');
INSERT INTO public.words(word, definition)VALUES ('fipple', 'A whistlelike mouthpiece for certain wind instruments, such as a recorder or flageolet, that channels the breath toward the sounding edge of a side opening');
INSERT INTO public.words(word, definition)VALUES ('fartlek', 'An athletic training technique, used especially in running, in which periods of intense effort alternate with periods of less strenuous effort in a continuous workout');
INSERT INTO public.words(word, definition)VALUES ('gaffle', 'A portable fork of iron or wood in which the heavy musket formerly in use was rested that it might be accurately aimed and fired');
INSERT INTO public.words(word, definition)VALUES ('zoster', 'A belt or girdle worn by men in ancient Greece');
INSERT INTO public.words(word, definition)VALUES ('myomancy', 'A kind of divination or method of foretelling future events by the movements of mice');
INSERT INTO public.words(word, definition)VALUES ('ferdwit', 'In Anglo-Saxon law, a fine imposed on persons for not going forth in a military expedition');
INSERT INTO public.words(word, definition)VALUES ('glendoveer', 'In Southeys poem “The Curse of Kehama” (1810), one of a race of beautiful sprites Glenoid notchSee notch');
INSERT INTO public.words(word, definition)VALUES ('calks', 'Plural form of calk');
INSERT INTO public.words(word, definition)VALUES ('barbellate', 'Botany  Finely or minutely barbed');
INSERT INTO public.words(word, definition)VALUES ('fud', 'The scut or tail of the hare, cony, etc');
INSERT INTO public.words(word, definition)VALUES ('fumet', 'The dung of the deer, hare, etc');
INSERT INTO public.words(word, definition)VALUES ('bundobust', 'System; discipline; orderliness');
INSERT INTO public.words(word, definition)VALUES ('swow', 'See swough');
INSERT INTO public.words(word, definition)VALUES ('floripondio', 'A plant, the Datura sanguinea, an infusion from whose seeds, prepared by the Peruvians, induces stupefaction, and, if much used, furious delirium');
INSERT INTO public.words(word, definition)VALUES ('crawthumper', 'Ireland ostentatiously pious person');
INSERT INTO public.words(word, definition)VALUES ('scarpology', 'See the quotation Also scarpalogy');
INSERT INTO public.words(word, definition)VALUES ('schemozzle', '(Yiddish) a confused situation or affair; a mess');
INSERT INTO public.words(word, definition)VALUES ('pokebag', 'The long-tailed titmouse or bottle-tit');
INSERT INTO public.words(word, definition)VALUES ('twankay', 'A brand of green tea grown and prepared in the western part of the province of Chĕ-kiang, China');
INSERT INTO public.words(word, definition)VALUES ('spizzerinctum', 'Chutzpah, guts, nerve, or backbone');
INSERT INTO public.words(word, definition)VALUES ('deasil', 'Motion according to the apparent course of the sun See withershins');
INSERT INTO public.words(word, definition)VALUES ('swallet', 'Prov Eng  Water breaking in upon the miners at their work; -- so called among tin miners');
INSERT INTO public.words(word, definition)VALUES ('kakkerlak', 'A cockroach Cassell, Nat Hist, VI 132');
INSERT INTO public.words(word, definition)VALUES ('allantiasis', 'A severe, sometimes fatal food poisoning caused by ingestion of food containing botulin');
INSERT INTO public.words(word, definition)VALUES ('fezzle', 'A litter of pigs');
INSERT INTO public.words(word, definition)VALUES ('stickit', 'Stuck');
INSERT INTO public.words(word, definition)VALUES ('melanotrichous', 'Having black hair; black-haired');
INSERT INTO public.words(word, definition)VALUES ('musnud', 'In India, a raised seat, overspread with carpets or embroidered cloth and furnished with pillows for the back and elbow');
INSERT INTO public.words(word, definition)VALUES ('doromania', 'An unusual urge or preoccupation with giving gifts');
INSERT INTO public.words(word, definition)VALUES ('pogonip', 'A frozen fog, formed in the coldest weather in the mountain valleys of Idaho, Nevada, and Colorado When inhaled it often produces severe pulmonary trouble');
INSERT INTO public.words(word, definition)VALUES ('oogonium', 'Any of the cells that give rise through mitosis to the oocytes and are found in the ovaries of vertebrates');
INSERT INTO public.words(word, definition)VALUES ('decussated', 'Simple past tense and past participle of decussate');
INSERT INTO public.words(word, definition)VALUES ('emunction', 'The act of blowing ones nose');
